config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'
  get 'integrations/google_gadget.xml' => 'integrations#google_gadget', :as => 'google_gadget'
  get 'integrations/get_applescript1.js' => 'integrations#get_applescript1'
  get 'integrations/get_applescript2.js' => 'integrations#get_applescript2'
  get 'integrations/get_quicksilver_applescript.js' => 'integrations#get_quicksilver_applescript'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt. 
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

app/models/recurring_todos/daily_recurring_todos_builder.rb
module RecurringTodos

  class DailyRecurringTodosBuilder < AbstractRecurringTodosBuilder
    attr_reader :recurring_todo, :pattern

    def initialize(user, attributes)
      super(user, attributes, DailyRepeatPattern)
    end

    def attributes_to_filter
      %w{daily_selector daily_every_x_days}
    end

    def map_attributes(mapping)
      mapping.set(:only_work_days, only_work_days?(@selector))
      mapping.set(:every_other1,   mapping.get(:daily_every_x_days))
      mapping.except(:daily_every_x_days)
    end

    def only_work_days?(daily_selector)
      { 'daily_every_x_day' => false,
        'daily_every_work_day' => true}[daily_selector]
    end

    def selector_key
      :daily_selector
    end

    def valid_selector?(selector)
      %w{daily_every_x_day daily_every_work_day}.include?(selector)
    end

  end

end

app/controllers/recurring_todos/form_helper.rb
module RecurringTodos

  class FormHelper

    def initialize(recurring_todo)
      @recurring_todo = recurring_todo

      @method_map = {
        # delegate daily_xxx to daily_pattern.xxx
        "daily"   => {prefix: "",    method: daily_pattern},
        "weekly"  => {prefix: "",    method: weekly_pattern},
        "monthly" => {prefix: "",    method: monthly_pattern},
        "yearly"  => {prefix: "",    method: yearly_pattern},
        # delegate on_xxx to weekly_pattern.on_xxx
        "on"      => {prefix: "on_", method: weekly_pattern}
      }
    end

    def create_pattern(pattern_class)
      pattern = pattern_class.new(@recurring_todo.user)
      pattern.build_from_recurring_todo(@recurring_todo)
      pattern
    end

    def daily_pattern
      @daily_pattern ||= create_pattern(DailyRepeatPattern)
    end

    def weekly_pattern
      @weekly_pattern ||= create_pattern(WeeklyRepeatPattern)
    end

    def monthly_pattern
      @monthly_pattern ||= create_pattern(MonthlyRepeatPattern)
    end

    def yearly_pattern
      @yearly_pattern ||= create_pattern(YearlyRepeatPattern)
    end

    def method_missing(method, *args)
      # delegate daily_xxx to daily_pattern, weekly_xxx to weekly_pattern, etc.
      if method.to_s =~ /^([^_]+)_(.+)$/
        return @method_map[$1][:method].send(@method_map[$1][:prefix]+$2, *args) unless @method_map[$1].nil?
      end

      # no match, let @recurring_todo handle it, or fail
      @recurring_todo.send(method, *args)
    end

  end

end

app/controllers/recurring_todos_controller.rb
class RecurringTodosController < ApplicationController

  helper :todos, :recurring_todos

  append_before_filter :init, :only => [:index, :new, :edit, :create]
  append_before_filter :get_recurring_todo_from_param, :only => [:destroy, :toggle_check, :toggle_star, :edit, :update]

  def index
    @page_title = t('todos.recurring_actions_title')
    @source_view = params['_source_view'] || 'recurring_todo'
    find_and_inactivate
    @recurring_todos = current_user.recurring_todos.active.includes(:tags, :taggings)
    @completed_recurring_todos = current_user.recurring_todos.completed.limit(10).includes(:tags, :taggings)

    @no_recurring_todos = @recurring_todos.count == 0
    @no_completed_recurring_todos = @completed_recurring_todos.count == 0
    @count = @recurring_todos.count

    @new_recurring_todo = RecurringTodo.new
  end

  def new
  end

  def show
  end

  def done
    @page_title = t('todos.completed_recurring_actions_title')
    @source_view = params['_source_view'] || 'recurring_todo'
    items_per_page = 20
    page = params[:page] || 1
    @completed_recurring_todos = current_user.recurring_todos.completed.paginate :page => params[:page], :per_page => items_per_page
    @total = @count = current_user.recurring_todos.completed.count
    @range_low = (page.to_i-1) * items_per_page + 1
    @range_high = @range_low + @completed_recurring_todos.size - 1
  end

  def edit
    @form_helper = RecurringTodos::FormHelper.new(@recurring_todo)

    respond_to do |format|
      format.js
    end
  end

  def update
    updater = RecurringTodos::RecurringTodosBuilder.new(current_user, update_recurring_todo_params)
    @saved = updater.update(@recurring_todo)

    @recurring_todo.reload

    respond_to do |format|
      format.js
    end
  end

  def create
    builder = RecurringTodos::RecurringTodosBuilder.new(current_user, all_recurring_todo_params)
    @saved = builder.save

    if @saved
      @recurring_todo = builder.saved_recurring_todo
      todo_saved = TodoFromRecurringTodo.new(current_user, @recurring_todo).create.nil? == false

      @status_message =
        t('todos.recurring_action_saved') + " / " +
        t("todos.new_related_todo_#{todo_saved ? "" : "not_"}created_short")

      @down_count = current_user.recurring_todos.active.count
      @new_recurring_todo = RecurringTodo.new
    else
      @recurring_todo = builder.recurring_todo
      @status_message = t('todos.error_saving_recurring')
    end

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @number_of_todos = @recurring_todo.todos.count

    # remove all references to this recurring todo
    @recurring_todo.clear_todos_association

    # delete the recurring todo
    @saved = @recurring_todo.destroy

    # count remaining recurring todos
    @active_remaining = current_user.recurring_todos.active.count
    @completed_remaining = current_user.recurring_todos.completed.count

    respond_to do |format|

      format.html do
        if @saved
          notify :notice, t('todos.recurring_deleted_success')
        else
          notify :error,  t('todos.error_deleting_recurring', :description => @recurring_todo.description)
        end
        redirect_to :action => 'index'
      end

      format.js do
        render
      end
    end
  end

  def toggle_check
    @saved = @recurring_todo.toggle_completion!

    @down_count = current_user.recurring_todos.active.count
    @active_remaining = @down_count
    @completed_remaining = 0

    if @recurring_todo.active?
      @completed_remaining = current_user.recurring_todos.completed.count

      # from completed back to active -> check if there is an active todo
      @active_todos = @recurring_todo.todos.active.count
      # create todo if there is no active todo belonging to the activated
      # recurring_todo
      @new_recurring_todo = TodoFromRecurringTodo.new(current_user, @recurring_todo).create if @active_todos == 0
    end

    respond_to do |format|
      format.js
    end
  end

  def toggle_star
    @recurring_todo.toggle_star!
    @saved = @recurring_todo.save!
    respond_to do |format|
      format.js
    end
  end

  private

  def recurring_todo_params
    params.require(:recurring_todo).permit(
      # model attributes
      :context_id, :project_id, :description, :notes, :state, :start_from,
      :ends_on, :end_date, :number_of_occurences, :occurences_count, :target,
      :show_from_delta, :recurring_period, :recurrence_selector, :every_other1,
      :every_other2, :every_other3, :every_day, :only_work_days, :every_count,
      :weekday, :show_always, :context_name, :project_name, :tag_list,
      # form attributes
      :recurring_period, :daily_selector, :monthly_selector, :yearly_selector,
      :recurring_target, :daily_every_x_days, :monthly_day_of_week,
      :monthly_every_x_day, :monthly_every_x_month2, :monthly_every_x_month,
      :monthly_every_xth_day, :recurring_show_days_before,
      :recurring_show_always, :weekly_every_x_week, :weekly_return_monday,
      :yearly_day_of_week, :yearly_every_x_day, :yearly_every_xth_day,
      :yearly_month_of_year2, :yearly_month_of_year,
      # derived attribues
      :weekly_return_monday, :weekly_return_tuesday, :weekly_return_wednesday,
      :weekly_return_thursday, :weekly_return_friday, :weekly_return_saturday, :weekly_return_sunday
      )
  end

  def all_recurring_todo_params
    # move context_name, project_name and tag_list into :recurring_todo hash for easier processing
    {
      context_name: :context_name,
      project_name: :project_name,
      tag_list:     :tag_list
    }.each do |target,source|
      move_into_recurring_todo_param(params, target, source)
    end
    recurring_todo_params
  end

  def update_recurring_todo_params
    # we needed to rename the recurring_period selector in the edit form because
    # the form for a new recurring todo and the edit form are on the same page.
    # Same goes for start_from and end_date
    params['recurring_todo']['recurring_period'] = params['recurring_edit_todo']['recurring_period']

    {
      context_name: :context_name,
      project_name: :project_name,
      tag_list:     :edit_recurring_todo_tag_list,
      end_date:     :recurring_todo_edit_end_date,
      start_from:   :recurring_todo_edit_start_from
    }.each do |target,source|
      move_into_recurring_todo_param(params, target, source)
    end

    # make sure that we set weekly_return_xxx to empty (space) when they are
    # not checked (and thus not present in params["recurring_todo"])
    %w{monday tuesday wednesday thursday friday saturday sunday}.each do |day|
      params["recurring_todo"]["weekly_return_#{day}"]=' ' if params["recurring_todo"]["weekly_return_#{day}"].nil?
    end

    recurring_todo_params
  end

  def move_into_recurring_todo_param(params, target, source)
    params[:recurring_todo][target] = params[source] unless params[source].blank?
  end

  def init
    @days_of_week   = (0..6).map{|i| [t('date.day_names')[i], i] }
    @months_of_year = (1..12).map{|i| [t('date.month_names')[i], i] }
    @xth_day = [[t('common.first'),1],[t('common.second'),2],[t('common.third'),3],[t('common.fourth'),4],[t('common.last'),5]]
    @projects = current_user.projects.includes(:default_context)
    @contexts = current_user.contexts
  end

  def get_recurring_todo_from_param
    @recurring_todo = current_user.recurring_todos.find(params[:id])
  end

  def find_and_inactivate
    # find active recurring todos without active todos and inactivate them

    current_user.recurring_todos.active.
      select("recurring_todos.id, recurring_todos.state").
      joins("LEFT JOIN todos fai_todos ON (recurring_todos.id = fai_todos.recurring_todo_id) AND (NOT fai_todos.state='completed')").
      where("fai_todos.id IS NULL").
      each { |rt| current_user.recurring_todos.find(rt.id).toggle_completion! }
  end

end

app/helpers/recurring_todos_helper.rb
module RecurringTodosHelper

  def recurring_todo_tag_list
    tags_except_starred = @recurring_todo.tags.reject{|t| t.name == Todo::STARRED_TAG_NAME}
    tag_list = tags_except_starred.
      collect{|t| content_tag(:span,link_to(t.name, tag_path(t.name)), :class => "tag #{t.label}")}.
      join('')
    return content_tag :span, tag_list.html_safe, :class => "tags"
  end

  def recurring_todo_remote_delete_icon
    link_to( image_tag_for_delete,
      recurring_todo_path(@recurring_todo), :id => "delete_icon_"+@recurring_todo.id.to_s,
      :class => "icon delete_icon", :title => t('todos.delete_recurring_action_title'), :x_confirm_message => t('todos.delete_recurring_action_confirm', :description => @recurring_todo.description))
  end

  def recurring_todo_remote_star_icon
    link_to( image_tag_for_star(@recurring_todo),
      toggle_star_recurring_todo_path(@recurring_todo), :id => "star_icon_"+@recurring_todo.id.to_s,
      :class => "icon star_item", :title => t('todos.star_action'))
  end

  def recurring_todo_remote_edit_icon
    if !@recurring_todo.completed?
      str = link_to( image_tag_for_edit(@recurring_todo),
        edit_recurring_todo_path(@recurring_todo),
        :class => "icon edit_icon", :id => "link_edit_recurring_todo_#{@recurring_todo.id}")
    else
      str = content_tag(:a, image_tag("blank.png"), :class => "icon")
    end
    str
  end

  def recurring_todo_remote_toggle_checkbox
    return check_box_tag("check_#{@recurring_todo.id}", toggle_check_recurring_todo_path(@recurring_todo), @recurring_todo.completed?, :class => 'item-checkbox')
  end

  private

  def image_tag_for_delete
    image_tag("blank.png", :title =>t('todos.delete_action'), :class=>"delete_item")
  end

  def image_tag_for_edit(todo)
    image_tag("blank.png", :title =>t('todos.edit_action'), :class=>"edit_item", :id=> dom_id(todo, 'edit_icon'))
  end
end

app/views/recurring_todos/_recurring_todo.html.erb
<% @recurring_todo = recurring_todo -%>
<div id="<%= dom_id(@recurring_todo)%>" class="recurring_todo item-container">
  <%= recurring_todo_remote_delete_icon %>
  <%= recurring_todo_remote_edit_icon -%>
  <%= recurring_todo_remote_star_icon %>
  <%= recurring_todo_remote_toggle_checkbox -%>
  <div class="rec_description">
    <span class="todo.descr"><%= sanitize(recurring_todo.description) %></span> <%= recurring_todo_tag_list %>
    <span class='recurrence_pattern'>
      [<%=  recurrence_pattern_as_text(@recurring_todo) %>]
    </span>
  </div>
</div>

app/views/recurring_todos/create.js.erb
<% if @saved -%>
  TracksPages.page_inform("<%=@status_message%>");
  add_recurring_todo_to_active_container();
  replace_form_with_empty_form();
  $( "#new-recurring-todo" ).dialog( "close" );
  TracksPages.set_page_badge(<%= @down_count %>);
<% else -%>
  TracksPages.show_errors(html_for_error_messages());
<% end -%>

function replace_form_with_empty_form() {
  $('div.recurring_container').html(html_for_empty_form());
}

function add_recurring_todo_to_active_container() {
  $('#recurring_todos_container').append(html_for_recurring_todo());
  $('#<%= dom_id(@recurring_todo)%>').effect('highlight', {}, 2000 );
  $('#recurring-todos-empty-nd').hide();
}

function html_for_recurring_todo() {
  return "<%= @saved ? js_render(@recurring_todo) : "" %>";
}

function html_for_empty_form() {
  return "<%= @saved ? js_render('recurring_todo_form') : "" %>";
}

function html_for_error_messages() {
  return "<%= js_error_messages_for(@recurring_todo) %>";
}

app/views/recurring_todos/destroy.js.erb
<%- if @saved -%>
  show_empty_messages();
  TracksPages.page_inform('<%=  escape_javascript(t('todos.recurring_deleted_success') + t('todos.recurring_pattern_removed', :count => pluralize(@number_of_todos,t('common.todo')))) %>');
  remove_recurring_todo_from_page();
<%- else -%>
  TracksPages.page_error('<%= t('todos.error_deleting_recurring', :description => @recurring_todo.description) %>');
<%- end -%>

function show_empty_messages() {
  <%- if @active_remaining == 0 -%>
    $('#recurring-todos-empty-nd').show();
  <%- end -%>
  <%- if @completed_remaining == 0 -%>
    $('#completed-empty-nd').show();
  <%- end -%>
}

function remove_recurring_todo_from_page() {
  $('#<%=dom_id(@recurring_todo)%>').slideUp(1000, function() {
    $('#<%=dom_id(@recurring_todo)%>').remove();
  });
}

app/views/recurring_todos/done.html.erb
<%
  paginate_options = {
    :class => :add_note_link,
    :previous_label => '&laquo; '+ t('common.previous'),
    :next_label     => t('common.next')+' &raquo;',
    :inner_window   => 2
  }
%>
<div id="display_box">
  <div class="container" id="completed_recurring_todos_container">
    <div class="paginate_header"><%= will_paginate @completed_recurring_todos, paginate_options %></div>
    <h2>
      <span id="completed-projects-count" class="badge"><%= "#{@total} (#{@range_low}-#{@range_high})" %></span>
      <%= t('todos.completed_recurring') %>
    </h2>
    <div id="completed_recurring_todos_container">
      <div id="completed-empty-nd" style="<%= @no_completed_recurring_todos ? 'display:block' : 'display:none'%>">
        <div class="message"><p><%= t('todos.no_completed_recurring') %></p></div>
      </div>
      <%= render :partial => @completed_recurring_todos %>
    </div>
    <div class="paginate_footer"><%= will_paginate @completed_recurring_todos, paginate_options %></div>
  </div>
</div>

app/views/recurring_todos/edit.js.erb
<% object_name = unique_object_name_for("edit_rec_todo_#{@recurring_todo.id}") -%>
var <%=object_name%> = {
  animate: function() {
    $('#edit-recurring-todo').html(<%=object_name%>.html_for_edit_form());
    $('#edit-recurring-todo').dialog( "open" );
  },
  html_for_edit_form: function() {
    return "<%= js_render('edit_form') %>";
  }
}
<%=object_name%>.animate();

app/views/recurring_todos/index.html.erb
<div id="display_box">
  <div class="container" id="active_recurring_todos_container">
    <h2><%= t('todos.recurring_todos') %></h2>
    <div id="recurring_todos_container">
      <div id="recurring-todos-empty-nd" style="<%= @no_recurring_todos ? 'display:block' : 'display:none'%>">
        <div class="message"><p><%= t('todos.no_recurring_todos') %></p></div>
      </div>
      <%= render :partial => @recurring_todos %>
    </div>
  </div>

  <div class="container" id="completed_recurring_todos_container">
    <div class=add_note_link><%= link_to t('common.show_all'), done_recurring_todos_path%></div>
    <h2><%= t('common.last') %> <%= t('todos.completed_recurring') %></h2>
    <div id="completed_recurring_todos_container">
      <div id="completed-empty-nd" style="<%= @no_completed_recurring_todos ? 'display:block' : 'display:none'%>">
        <div class="message"><p><%= t('todos.no_completed_recurring') %></p></div>
      </div>
      <%= render :partial => @completed_recurring_todos %>
    </div>
  </div>
</div>
<div id="input_box">
  <div id="recurring_new_container">
    <a href='#' id="add-new-recurring-todo"><%= image_tag("add.png", {:alt => "[ADD]"})-%><%= t('todos.add_new_recurring') %></a>
  </div>
</div>

<div id="new-recurring-todo" class="new-form" title="<%= t('todos.add_new_recurring') %>">
  <%= render :partial => "recurring_todo_form" %>
</div>
<div id="edit-recurring-todo" class="edit-form" style="display:none" title="<%= t('todos.edit_recurring_todo') %>">
  <div class='placeholder'>This should not be visible</div>
</div>

app/views/recurring_todos/new.html.erb
<%= render :partial => "recurring_todo_form" %>

app/views/recurring_todos/toggle_check.js.erb
<%- unless @saved -%>
  TracksPages.page_error('<%=  t('todos.error_completing_todo', :description => @recurring_todo.description) %>');
<%- else
  object_name = unique_object_name_for("toggle_check_rec")
-%>
var <%=object_name%> = {
  animate: function() {
    TracksPages.set_page_badge(<%= @down_count %>);
    <%=object_name%>.remove_old_and_add_updated_recurring_todo();
    <%= "#{object_name}.inform_if_new_todo_created();" if @new_recurring_todo -%>
  },
  inform_if_new_todo_created: function() {
    TracksPages.page_inform('<%=  t('todos.new_related_todo_created') %>');
  },
  remove_old_and_add_updated_recurring_todo: function() {
    $('#<%=dom_id(@recurring_todo)%>').slideUp(1000, function() {
      $('#<%=dom_id(@recurring_todo)%>').remove();
      <%=object_name%>.show_empty_messages();

      <%- if @recurring_todo.completed? -%>
        <%=object_name%>.add_recurring_todo_to_completed_container();
      <%- else -%>
        <%=object_name%>.add_recurring_todo_to_active_container();
      <%- end -%>
    });
  },
  add_recurring_todo_to_completed_container: function() {
    $('#completed_recurring_todos_container').append(<%=object_name%>.html_for_recurring_todo());
    $('#<%= dom_id(@recurring_todo)%>').effect('highlight', {}, 2000 );
    $('#completed-empty-nd').hide();
  },
  add_recurring_todo_to_active_container: function() {
    $('#recurring_todos_container').append(<%=object_name%>.html_for_recurring_todo());
    $('#<%= dom_id(@recurring_todo)%>').effect('highlight', {}, 2000 );
    $('#recurring-todos-empty-nd').hide();
  },
  show_empty_messages: function() {
    <%- if @active_remaining == 0 -%>
      $('#recurring-todos-empty-nd').show();
    <%- end -%>
    <%- if @completed_remaining == 0 -%>
      $('#completed-empty-nd').show();
    <%- end -%>
  },
  html_for_recurring_todo: function() {
    return "<%= @saved ? js_render(@recurring_todo) : "" %>";
  }
}

<%=object_name%>.animate();
<%- end -%>

app/views/recurring_todos/toggle_star.js.erb
<%- if @saved -%>
  $('div#recurring_todo_<%= @recurring_todo.id %> a.star_item img').toggleClass('starred');
<%- else -%>
  TracksPages.page_error('<%= t('todos.error_starring_recurring', :description => @recurring_todo.description) %>');
<%- end -%>